# Generated by Django 4.2.13 on 2026-05-28 10:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('SAP_FLAT_FILE', 'SAP Flat File Export'), ('UTILITY_CSV', 'Utility CSV Export'), ('TRAVEL_CONCUR', 'SAP Concur Export')], max_length=30)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')], validators=[django.core.validators.MinValueValidator(1)])),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingestion_datasource',
            },
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SUPERSEDED', 'Superseded')], default='PENDING', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=500)),
                ('source_file_hash', models.CharField(blank=True, max_length=64)),
                ('row_count_raw', models.IntegerField(blank=True, null=True)),
                ('row_count_valid', models.IntegerField(blank=True, null=True)),
                ('row_count_failed', models.IntegerField(blank=True, null=True)),
                ('error_summary', models.JSONField(blank=True, null=True)),
                ('pipeline_version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'db_table': 'ingestion_ingestionbatch',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.SmallIntegerField(default=1)),
                ('is_current', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[('FUEL_COMBUSTION', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity'), ('FLIGHT', 'Business Flight'), ('HOTEL', 'Hotel Stay'), ('GROUND_TRANSPORT', 'Ground Transport'), ('DISTRICT_HEAT', 'District Heat/Steam'), ('REFRIGERANT', 'Refrigerant Leakage'), ('OTHER', 'Other')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('unit', models.CharField(max_length=30)),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_original', models.CharField(blank=True, max_length=30)),
                ('conversion_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('conversion_source', models.CharField(blank=True, max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_id', models.CharField(blank=True, max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('supplier', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ingestion_normalizedemissionrow',
            },
        ),
        migrations.CreateModel(
            name='RawEmissionRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField()),
                ('source_type', models.CharField(max_length=30)),
                ('scope', models.SmallIntegerField()),
                ('raw_data', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_REVIEW', 'Needs Review')], default='PENDING', max_length=30)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ingestion_rawemissionrow',
            },
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(max_length=50)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=10)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_issues', to='ingestion.rawemissionrow')),
            ],
            options={
                'db_table': 'ingestion_validationissue',
            },
        ),
    ]
