# Generated by Django 4.2.13 on 2026-05-28 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='validationissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='validationissue',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='rawemissionrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionbatch'),
        ),
        migrations.AddField(
            model_name='rawemissionrow',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rawemissionrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_rows', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrow',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_rows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='normalizedemissionrow',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='ingestion.normalizedemissionrow'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrow',
            name='raw_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_versions', to='ingestion.rawemissionrow'),
        ),
        migrations.AddField(
            model_name='normalizedemissionrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='ingestion.datasource'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='ingestionbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasource',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='validationissue',
            index=models.Index(fields=['raw_row', 'is_resolved'], name='ingestion_v_raw_row_0de4ad_idx'),
        ),
        migrations.AddIndex(
            model_name='validationissue',
            index=models.Index(fields=['tenant', 'severity', 'is_resolved'], name='ingestion_v_tenant__1a7773_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemissionrow',
            index=models.Index(fields=['tenant', 'status'], name='ingestion_r_tenant__7d6043_idx'),
        ),
        migrations.AddIndex(
            model_name='rawemissionrow',
            index=models.Index(fields=['batch', 'row_index'], name='ingestion_r_batch_i_313b29_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rawemissionrow',
            unique_together={('batch', 'row_index')},
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrow',
            index=models.Index(fields=['tenant', 'is_current', 'period_start'], name='ingestion_n_tenant__31b205_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedemissionrow',
            index=models.Index(fields=['raw_row', '-version'], name='ingestion_n_raw_row_e2e559_idx'),
        ),
        migrations.AddConstraint(
            model_name='normalizedemissionrow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('raw_row',), name='unique_current_version_per_raw_row'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['tenant', '-uploaded_at'], name='ingestion_i_tenant__c7aeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionbatch',
            index=models.Index(fields=['source_file_hash'], name='ingestion_i_source__97c469_idx'),
        ),
        migrations.AddConstraint(
            model_name='datasource',
            constraint=models.CheckConstraint(check=models.Q(('scope__in', [1, 2, 3])), name='valid_scope'),
        ),
    ]
