# Generated by Django 4.2.13 on 2026-05-28 10:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=30)),
                ('co2_factor', models.DecimalField(decimal_places=10, max_digits=18)),
                ('ch4_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('n2o_factor', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('co2e_factor', models.DecimalField(decimal_places=10, max_digits=18)),
                ('gwp_version', models.CharField(blank=True, max_length=20)),
                ('source', models.CharField(max_length=200)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'emissions_emissionfactor',
                'indexes': [models.Index(fields=['activity_type', 'valid_from', 'valid_to'], name='emissions_e_activit_d690ff_idx'), models.Index(fields=['country_code'], name='emissions_e_country_c213e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmissionCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co2e_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('co2_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('ch4_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('n2o_kg', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('calculation_method', models.CharField(choices=[('ACTIVITY_BASED', 'Activity Based'), ('SPEND_BASED', 'Spend Based')], default='ACTIVITY_BASED', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculator_version', models.CharField(default='1.0.0', max_length=20)),
                ('emission_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='emissions.emissionfactor')),
            ],
            options={
                'db_table': 'emissions_emissioncalculation',
            },
        ),
    ]
