# Generated by Django 4.2.13 on 2026-05-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissioncalculation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculation',
            index=models.Index(fields=['normalized_row'], name='emissions_e_normali_5a598d_idx'),
        ),
        migrations.AddIndex(
            model_name='emissioncalculation',
            index=models.Index(fields=['tenant', 'calculated_at'], name='emissions_e_tenant__fd7e06_idx'),
        ),
    ]
