# Generated by Django 4.2.13 on 2026-05-28 10:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ROW_APPROVED', 'Row Approved'), ('ROW_REJECTED', 'Row Rejected'), ('ROW_EDITED', 'Row Edited'), ('ROW_DELETED', 'Row Soft Deleted'), ('BATCH_UPLOADED', 'Batch Uploaded'), ('BATCH_SUPERSEDED', 'Batch Superseded'), ('ISSUE_RESOLVED', 'Validation Issue Resolved'), ('BULK_APPROVE', 'Bulk Approval'), ('BULK_REJECT', 'Bulk Rejection'), ('USER_INVITED', 'User Invited'), ('SOURCE_CONFIGURED', 'Data Source Configured')], max_length=50)),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_event_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_auditevent',
                'ordering': ['-created_at'],
            },
        ),
    ]
